In [1]:
import numpy as np
import pandas as pd

In [2]:
link = r"https://archive.ics.uci.edu/ml/machine-learning-databases/00502/online_retail_II.xlsx"
df1 = pd.read_excel(link, sheet_name='Year 2009-2010')
df2 = pd.read_excel(link, sheet_name='Year 2010-2011')

In [3]:
df1.shape, df2.shape

((525461, 8), (541910, 8))

In [4]:
df1.info()

<class 'pandas.DataFrame'>
RangeIndex: 525461 entries, 0 to 525460
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      525461 non-null  object
 1   StockCode    525461 non-null  object
 2   Description  522533 non-null  object
 3   Quantity     525461 non-null  int64
 4   InvoiceDate  525461 non-null  datetime64[us]
 5   Price        525461 non-null  float64
 6   Customer ID  417534 non-null  float64
 7   Country      525461 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 32.1+ MB

In [5]:
df2.info()

<class 'pandas.DataFrame'>
RangeIndex: 541910 entries, 0 to 541909
Data columns (total 8 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      541910 non-null  object
 1   StockCode    541910 non-null  object
 2   Description  540456 non-null  object
 3   Quantity     541910 non-null  int64
 4   InvoiceDate  541910 non-null  datetime64[us]
 5   Price        541910 non-null  float64
 6   Customer ID  406830 non-null  float64
 7   Country      541910 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 33.1+ MB

In [41]:
df = pd.concat([df1, df2], ignore_index=True)
df.shape

(1067371, 8)

In [42]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 1067371 entries, 0 to 1067370
Data columns (total 8 columns):
 #   Column       Non-Null Count    Dtype
---  ------       --------------    -----
 0   Invoice      1067371 non-null  object
 1   StockCode    1067371 non-null  object
 2   Description  1062989 non-null  object
 3   Quantity     1067371 non-null  int64
 4   InvoiceDate  1067371 non-null  datetime64[us]
 5   Price        1067371 non-null  float64
 6   Customer ID  824364 non-null   float64
 7   Country      1067371 non-null  str
dtypes: datetime64[us](1), float64(2), int64(1), object(3), str(1)
memory usage: 65.1+ MB

In [43]:
df.dropna(subset='Customer ID', inplace=True)
df.shape

(824364, 8)

In [44]:
df.iloc[100:200]

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country
100,489442,22271,FELTCRAFT DOLL ROSIE,6,2009-12-01 09:46:00,2.95,13635.0,United Kingdom
101,489442,22272,FELTCRAFT DOLL MARIA,6,2009-12-01 09:46:00,2.95,13635.0,United Kingdom
102,489442,85123A,WHITE HANGING HEART T-LIGHT HOLDER,6,2009-12-01 09:46:00,2.95,13635.0,United Kingdom
103,489442,21582,KINGS CHOICE SMALL TUBE MATCHES,20,2009-12-01 09:46:00,1.65,13635.0,United Kingdom
104,489442,21586,KINGS CHOICE GIANT TUBE MATCHES,12,2009-12-01 09:46:00,2.55,13635.0,United Kingdom
...,...,...,...,...,...,...,...,...
195,489450,22090,PAPER BUNTING RETRO SPOTS,12,2009-12-01 10:36:00,2.95,16321.0,Australia
196,C489459,90200A,PURPLE SWEETHEART BRACELET,-3,2009-12-01 10:44:00,4.25,17592.0,United Kingdom
197,C489459,90200D,PINK SWEETHEART BRACELET,-3,2009-12-01 10:44:00,4.25,17592.0,United Kingdom
198,C489459,90200B,BLACK SWEETHEART BRACELET,-3,2009-12-01 10:44:00,4.25,17592.0,United Kingdom
199,C489459,90200E,GREEN SWEETHEART BRACELET,-3,2009-12-01 10:44:00,4.25,17592.0,United Kingdom

In [58]:
df = df[(~df['Invoice'].astype('str').str.startswith('C')) | (df['Quantity'].gt(0))]

In [59]:
df['Revenue'] = df['Quantity'] * df['Price']

In [60]:
df.info()

<class 'pandas.DataFrame'>
Index: 805620 entries, 0 to 1067370
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Invoice      805620 non-null  datetime64[ns]
 1   StockCode    805620 non-null  object
 2   Description  805620 non-null  object
 3   Quantity     805620 non-null  int64
 4   InvoiceDate  805620 non-null  datetime64[us]
 5   Price        805620 non-null  float64
 6   Customer ID  805620 non-null  float64
 7   Country      805620 non-null  str
 8   Revenue      805620 non-null  float64
dtypes: datetime64[ns](1), datetime64[us](1), float64(3), int64(1), object(2), str(1)
memory usage: 61.5+ MB

In [75]:
df['month'] = df['InvoiceDate'].dt.to_period('M')
df.head()

,Invoice,StockCode,Description,Quantity,InvoiceDate,Price,Customer ID,Country,Revenue,month
0,1970-01-01 00:00:00.000489434,85048,15CM CHRISTMAS GLASS BALL 20 LIGHTS,12,2009-12-01 07:45:00,6.95,13085.0,United Kingdom,83.4,2009-12
1,1970-01-01 00:00:00.000489434,79323P,PINK CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009-12
2,1970-01-01 00:00:00.000489434,79323W,WHITE CHERRY LIGHTS,12,2009-12-01 07:45:00,6.75,13085.0,United Kingdom,81.0,2009-12
3,1970-01-01 00:00:00.000489434,22041,"RECORD FRAME 7"" SINGLE SIZE",48,2009-12-01 07:45:00,2.10,13085.0,United Kingdom,100.8,2009-12
4,1970-01-01 00:00:00.000489434,21232,STRAWBERRY CERAMIC TRINKET BOX,24,2009-12-01 07:45:00,1.25,13085.0,United Kingdom,30.0,2009-12

In [79]:
month_rev = df.groupby(by='month')['Revenue'].sum().sort_index()
month_rev

month
2009-12     686654.160
2010-01     557319.062
2010-02     506371.066
2010-03     699608.991
2010-04     594609.192
2010-05     599985.790
2010-06     639066.580
2010-07     591636.740
2010-08     604242.650
2010-09     831615.001
2010-10    1036680.000
2010-11    1172336.042
2010-12     884591.890
2011-01     569445.040
2011-02     447137.350
2011-03     595500.760
2011-04     469200.361
2011-05     678594.560
2011-06     661213.690
2011-07     600091.011
2011-08     645343.900
2011-09     952838.382
2011-10    1039318.790
2011-11    1161817.380
2011-12     518210.790
Freq: M, Name: Revenue, dtype: float64

In [81]:
month_rev.index, month_rev.values

(PeriodIndex(['2009-12', '2010-01', '2010-02', '2010-03', '2010-04', '2010-05',
              '2010-06', '2010-07', '2010-08', '2010-09', '2010-10', '2010-11',
              '2010-12', '2011-01', '2011-02', '2011-03', '2011-04', '2011-05',
              '2011-06', '2011-07', '2011-08', '2011-09', '2011-10', '2011-11',
              '2011-12'],
             dtype='period[M]', name='month'),
 array([ 686654.16 ,  557319.062,  506371.066,  699608.991,  594609.192,
         599985.79 ,  639066.58 ,  591636.74 ,  604242.65 ,  831615.001,
        1036680.   , 1172336.042,  884591.89 ,  569445.04 ,  447137.35 ,
         595500.76 ,  469200.361,  678594.56 ,  661213.69 ,  600091.011,
         645343.9  ,  952838.382, 1039318.79 , 1161817.38 ,  518210.79 ]))